owner: kalagiri-bot
repo: status

sites:
  - name: thekrishna.in (Portfolio)
    url: 'https://thekrishna.in/'
    icon: 'https://thekrishna.in/favicon.ico'
  - name: Nextcloud (FL)
    url: $NEXTCLOUD_URL
    icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Nextcloud_Logo.svg/141px-Nextcloud_Logo.svg.png'
    maxResponseTime: 5000
    
assignees:
  - bearlike
  
status-website:
  cname: status.thekrishna.in
  favicon: 'https://thekrishna.in/assets/img/KK.png'
  faviconSvg: 'https://thekrishna.in/assets/img/KK.svg'
  logoUrl: 'https://thekrishna.in/assets/img/KK.svg'
  name: Uptime
  introTitle: Website monitoring and status page.
  introMessage: Don't wait for the metrics to come to you.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: 'https://thekrishna.in/'
    - title: GitHub
      href: 'https://github.com/bearlike'
  metaTags:
    - name: robots
      content: noindex
      
commitMessages:
  commitAuthorName: 'Krishna Alagiri [ʙᴏᴛ]'
  commitAuthorEmail: 92151357+kalagiri-bot@users.noreply.github.com
user-agent: kalagiri-bot
i18n:
    footer: Managed by [Krishnakanth Alagiri](https://thekrishna.in)
  
workflowSchedule:
  graphs: 0 * * * *
  responseTime: 0 */6 * * *
  staticSite: 0 * * * *
  summary: 0 * * * *
  updateTemplate: 0 * * * *
  updates: 0 * * * *
  uptime: */30 * * * *
