name: "Alerts and Notifications"

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r notify-bot/requirements.txt
        
    - name: Send Discord Notification
      run: python notify-bot/discord.py ${{ github.event.issue.number }} ${{ secrets.NOTIFICATION_DISCORD_WEBHOOK_URL }}

    - name: Send Email Notification
      run: | 
        cd notify-bot/
        python mail.py ${{ github.event.issue.number }} ${{ secrets.SMTP_USER }} ${{ secrets.SMTP_PASSWORD }} ${{ secrets.SMTP_SERVER }} ${{ secrets.SMTP_FROM_EMAIL }} ${{ secrets.SMTP_TO_EMAIL }} 

